apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-service-clusterip
#   namespace: monitoring
#   labels:
#     app: prometheus
#   annotations:
#     prometheus.io/scrape: "true"                     # Prometheus को scrape करना है
#     prometheus.io/port: "9090"                       # किस पोर्ट पर scrape करना है
#     prometheus.io/path: "/metrics"                   # मे트्रिक्स का path
#     prometheus.io/scheme: "http"                     # स्कीम http है या https
#     prometheus.io/instance: "prometheus"             # instance का नाम
#     prometheus.io/namespace: "monitoring"            # namespace
#     prometheus.io/monitoring: "true"                 # मॉनिटरिंग enabled है
#     prometheus.io/description: "Prometheus monitoring service"
#     prometheus.io/created-by: "kubernetes"
#     prometheus.io/version: "v2.30.3"
#     prometheus.io/labels: "app=prometheus,component=server"
#     prometheus.io/health-check: "true"
#     prometheus.io/health-check-path: "/-/healthy"
# spec:
#   selector:
#     app: prometheus
#   ports:
#     - port: 9090             # ClusterIP पोर्ट
#       targetPort: 9090       # कंटेनर पोर्ट
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus-service-lb
#   namespace: monitoring
# spec:
#   type: LoadBalancer
#   selector:
#     app: prometheus
#   ports:
#     - name: web
#       port: 80
#       targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
    release: prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30090  # Accessible on <NodeIP>:30090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
      release: prometheus
  template:
    metadata:
      labels:
        app: prometheus
        release: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          volumeMounts:
            - mountPath: /etc/prometheus
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: prometheus-config