apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
  namespace: monitoring
  labels:
    app: my-app
    version: v1
  # annotations:   # if you are not using PodMonitor, then use annotations to scrape metrics
  #   prometheus.io/scrape: "true"
  #   prometheus.io/path: "/metrics"
  #   prometheus.io/port: "8000"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: v1
  template:
    metadata:
      labels:
        app: my-app
        version: v1
     
    spec:
      containers:
      - name: django
        image: shailesh49/myappv1:latest
        ports:
        - name: web
          containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "mysite.settings"
       
  