apiVersion: v1
kind: Service
metadata:
  name: app-v1
  namespace: monitoring
  labels:
    app: my-app
    version: v1
spec:
  selector:
    app: my-app
    version: v1
  ports:
  - name: web
    port: 8000
    targetPort: 8000

