apiVersion: v1
kind: Service
metadata:
  name: app-v1
  namespace: monitoring
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: metrics
      port: 9113
      targetPort: 9113

