name: Django Projects CI

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   types: [closed]
  #   branches: [ "main" ]

jobs:
  build:
   # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    # strategy:
    #   max-parallel: 4
    #   matrix:
    #     python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout full repo with submodules
      uses: actions/checkout@v4
      with:
         fetch-depth: 0        # git log, tags, semantic-release के लिए ज़रूरी  केवल 1 latest commit को डाउनलोड करता है (default)
         submodules: true      # अगर repo में git submodules हैं

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip                 # cd projects/mysite
        pip install -r projects/mysite/requirements.txt     #pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd projects/mysite 
        python manage.py test
