name:  Django Project CI Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: | 
          cd projects/mysite
           #docker build . --file Dockerfile --tag shailesh49/djangoapp:$(date +%s)
           docker build . --file Dockerfile --tag shailesh49/djangoapp:${{ github.run_number }}
           docker images
